name: Publish Package to GitHub NPM Registry

on: 
  release:
    type: published
    
jobs:
    npm-package:
      permissions:
        packages: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - uses: action/setup-node@v4
          with:
            version: '20.x'
            registry-url: 'https://npm.pkg.github.com/'
        - run: npm install
        - run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.Github_token }}
            
