name: Publish Package to GitHub NPM Registry

on: 
  release:
    type: published
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: install nodeJS with version 20.x
          uses: action/setup-node@v4
          with:
            version: '20.x'
            registry-url: 'https://npm.pkg.github.com/'
        - name: install npm
          run: npm install
